const stories = [
	{
		_id: 1,
		author: "Adrienne LaFrance",
		story:
			"The Doomsday Machine was never supposed to exist. It was meant to be a thought experiment that went like this: Imagine a device built with the sole purpose of destroying all human life. Now suppose that machine is buried deep underground, but connected to a computer, which is in turn hooked up to sensors in cities and towns across the United States The sensors are designed to sniff out signs of the impending apocalypse—not to prevent the end of the world, but to complete it. If radiation levels suggest nuclear explosions in, say, three American cities simultaneously, the sensors notify the Doomsday Machine, which is programmed to detonate several nuclear warheads in response. At that point, there is no going back. The fission chain reaction that produces an atomic explosion is initiated enough times over to extinguish all life on Earth. There is a terrible flash of light, a great booming sound, then a sustained roar. We have a word for the scale of destruction that the Doomsday Machine would unleash: megadeath. Nobody is pining for megadeath. But megadeath is not the only thing that makes the Doomsday Machine petrifying. The real terror is in its autonomy, this idea that it would be programmed to detect a series of environmental inputs, then to act, without human interference. “There is no chance of human intervention, control, and final decision,” wrote the military strategist Herman Kahn in his 1960 book, On Thermonuclear War, which laid out the hypothetical for a Doomsday Machine. The concept was to render nuclear war unwinnable, and therefore unthinkable. Kahn concluded that automating the extinction of all life on Earth would be immoral. Even an infinitesimal risk of error is too great to justify the Doomsday Machine’s existence. “And even if we give up the computer and make the Doomsday Machine reliably controllable by decision makers,” Kahn wrote, “it is still not controllable enough.” No machine should be that powerful by itself—but no one person should be either. The Soviets really did make a version of the Doomsday Machine during the Cold War. They nicknamed it “Dead Hand.” But so far, somewhat miraculously, we have figured out how to live with the bomb. Now we need to learn how to survive the social web.",
		title: "Facebook Is a Doomsday Machine",
	},
	{
		_id: 2,
		author: "Cheryl Katz",
		story:
			"The twin smokestacks of the Moss Landing Power Plant tower over Monterey Bay. Visible for miles along this picturesque stretch of the north Californian coast, the 500-foot-tall (150m) pillars crown what was once California's largest electric power station – a behemoth natural gas-fired generator. Today, as California steadily moves to decarbonise its economy, those stacks are idle and the plant is largely mothballed. Instead, the site is about to begin a new life as the world's largest battery, storing excess energy when solar panels and wind farms are producing electricity and feeding it back into the grid when they're not. Inside a cavernous turbine building, a 300-megawatt lithium-ion battery is currently being readied for operation, with another 100-megawatt battery to come online in 2021.These aren't the only super-sized batteries that will soon be operating at the Moss Landing plant. An additional 182.5 megawatts produced by 256 Tesla megapack batteries are scheduled to begin feeding into California's electric grid in mid-2021, with plans to eventually add enough capacity at the site to power every home in nearby San Francisco for six hours, according to the Bay Area utility, Pacific Gas and Electric, which will own and operate the system. Elsewhere in California, a 250-megawatt storage project went online this year in San Diego, construction has begun on a 150-megawatt system near San Francisco, a 100-megawatt battery project is nearing completion in Long Beach, and a number of others are in various stages of development around the state.California is currently the global leader in the effort to balance the intermittency of renewable energy in electric grids with utility-scale batteries, but the rest of the world is rapidly following suit. Recently announced plans range from a 409-megawatt system in South Florida, to a 320-megawatt plant near London in the UK, to a 200-megawatt facility in Lithuania and a 112-megawatt unit in Chile.",
		title: "The batteries that could make fossil fuels obsolete",
	},
	{
		_id: 3,
		author: "Aysha Imtiaz",
		story:
			"When this year’s monsoon season hit Bangladesh, it wasn’t an ordinary flood. Within weeks, one quarter of the country was underwater. “We’ve been managing flood relief efforts in the region for 10 years,” says Ahmed Imtiaz Jami, president of Obhizatrik Foundation, a charity and volunteering organisation in Bangladesh. But the 2020 floods were a step-change. “It just wasn’t the same.” Nearly 1.3 million homes were damaged, hundreds of thousands of people were marooned, and hundreds died.Yet monsoon flooding is increasingly being recognised to be as vital to the delta nation as it is destructive, raising a difficult question: how do you allow the life-restoring properties of floods to continue nourishing the land, while providing protection against the worsening floods of the future? A dizzying latticework of 230 rivers crisscrosses Bangladesh. Three of those rivers are the massive Brahmaputra-Jamuna, the Ganges (or Padma, as it is known in Bangladesh) and the Meghna, which eventually empty into the Bay of Bengal. Along with water, these river systems carries between 1-1.4 billion tonnes of fertile silt through the country every year, forming the foundation for much of the country’s agriculture. They are also the reason why Bangladesh is one of the world’s hardest hit countries by climate change.",
		title: "The nation learning to embrace flooding",
	},
	{
		_id: 4,
		author: "Catherine Early",
		story:
			"Cornwall, 1864. A hot spring is discovered nearly 450m (1,485ft) below ground in the Wheal Clifford, a copper mine just outside the mining town of Redruth. Glass bottles are immersed to their necks in its bubbling waters, carefully sealed and sent off for testing. The result is the discovery of so great a quantity of lithium – eight or 10 times as much per gallon as had been found in any hot spring previously analysed – that scientists suspect “it may prove of great commercial value”.But 19th-Century England had little need for the element, and this 50C (122F) lithium-rich water continued steaming away in the dark for more than 150 years.Fast forward to autumn 2020, and a site nearby the Wheal Clifford in Cornwall has been confirmed as having some of the world’s highest grades of lithium in geothermal waters. The commercial use for lithium in the 21st Century could not be clearer. It is found not only inside smart phones and laptops, but is now vital to the clean energy transition, for the batteries that power electric vehicles and store energy so renewable power can be released steadily and reliably.",
		title: "The new 'gold rush' for green lithium",
	},

	{
		_id: 5,
		author: "Adrienne LaFrance",
		story:
			"The Doomsday Machine was never supposed to exist. It was meant to be a thought experiment that went like this: Imagine a device built with the sole purpose of destroying all human life. Now suppose that machine is buried deep underground, but connected to a computer, which is in turn hooked up to sensors in cities and towns across the United States The sensors are designed to sniff out signs of the impending apocalypse—not to prevent the end of the world, but to complete it. If radiation levels suggest nuclear explosions in, say, three American cities simultaneously, the sensors notify the Doomsday Machine, which is programmed to detonate several nuclear warheads in response. At that point, there is no going back. The fission chain reaction that produces an atomic explosion is initiated enough times over to extinguish all life on Earth. There is a terrible flash of light, a great booming sound, then a sustained roar. We have a word for the scale of destruction that the Doomsday Machine would unleash: megadeath. Nobody is pining for megadeath. But megadeath is not the only thing that makes the Doomsday Machine petrifying. The real terror is in its autonomy, this idea that it would be programmed to detect a series of environmental inputs, then to act, without human interference. “There is no chance of human intervention, control, and final decision,” wrote the military strategist Herman Kahn in his 1960 book, On Thermonuclear War, which laid out the hypothetical for a Doomsday Machine. The concept was to render nuclear war unwinnable, and therefore unthinkable. Kahn concluded that automating the extinction of all life on Earth would be immoral. Even an infinitesimal risk of error is too great to justify the Doomsday Machine’s existence. “And even if we give up the computer and make the Doomsday Machine reliably controllable by decision makers,” Kahn wrote, “it is still not controllable enough.” No machine should be that powerful by itself—but no one person should be either. The Soviets really did make a version of the Doomsday Machine during the Cold War. They nicknamed it “Dead Hand.” But so far, somewhat miraculously, we have figured out how to live with the bomb. Now we need to learn how to survive the social web.",
		title: "Facebook Is a Doomsday Machine",
	},
	{
		_id: 6,
		author: "Cheryl Katz",
		story:
			"The twin smokestacks of the Moss Landing Power Plant tower over Monterey Bay. Visible for miles along this picturesque stretch of the north Californian coast, the 500-foot-tall (150m) pillars crown what was once California's largest electric power station – a behemoth natural gas-fired generator. Today, as California steadily moves to decarbonise its economy, those stacks are idle and the plant is largely mothballed. Instead, the site is about to begin a new life as the world's largest battery, storing excess energy when solar panels and wind farms are producing electricity and feeding it back into the grid when they're not. Inside a cavernous turbine building, a 300-megawatt lithium-ion battery is currently being readied for operation, with another 100-megawatt battery to come online in 2021.These aren't the only super-sized batteries that will soon be operating at the Moss Landing plant. An additional 182.5 megawatts produced by 256 Tesla megapack batteries are scheduled to begin feeding into California's electric grid in mid-2021, with plans to eventually add enough capacity at the site to power every home in nearby San Francisco for six hours, according to the Bay Area utility, Pacific Gas and Electric, which will own and operate the system. Elsewhere in California, a 250-megawatt storage project went online this year in San Diego, construction has begun on a 150-megawatt system near San Francisco, a 100-megawatt battery project is nearing completion in Long Beach, and a number of others are in various stages of development around the state.California is currently the global leader in the effort to balance the intermittency of renewable energy in electric grids with utility-scale batteries, but the rest of the world is rapidly following suit. Recently announced plans range from a 409-megawatt system in South Florida, to a 320-megawatt plant near London in the UK, to a 200-megawatt facility in Lithuania and a 112-megawatt unit in Chile.",
		title: "The batteries that could make fossil fuels obsolete",
	},
	{
		_id: 7,
		author: "Aysha Imtiaz",
		story:
			"When this year’s monsoon season hit Bangladesh, it wasn’t an ordinary flood. Within weeks, one quarter of the country was underwater. “We’ve been managing flood relief efforts in the region for 10 years,” says Ahmed Imtiaz Jami, president of Obhizatrik Foundation, a charity and volunteering organisation in Bangladesh. But the 2020 floods were a step-change. “It just wasn’t the same.” Nearly 1.3 million homes were damaged, hundreds of thousands of people were marooned, and hundreds died.Yet monsoon flooding is increasingly being recognised to be as vital to the delta nation as it is destructive, raising a difficult question: how do you allow the life-restoring properties of floods to continue nourishing the land, while providing protection against the worsening floods of the future? A dizzying latticework of 230 rivers crisscrosses Bangladesh. Three of those rivers are the massive Brahmaputra-Jamuna, the Ganges (or Padma, as it is known in Bangladesh) and the Meghna, which eventually empty into the Bay of Bengal. Along with water, these river systems carries between 1-1.4 billion tonnes of fertile silt through the country every year, forming the foundation for much of the country’s agriculture. They are also the reason why Bangladesh is one of the world’s hardest hit countries by climate change.",
		title: "The nation learning to embrace flooding",
	},
	{
		_id: 8,
		author: "Catherine Early",
		story:
			"Cornwall, 1864. A hot spring is discovered nearly 450m (1,485ft) below ground in the Wheal Clifford, a copper mine just outside the mining town of Redruth. Glass bottles are immersed to their necks in its bubbling waters, carefully sealed and sent off for testing. The result is the discovery of so great a quantity of lithium – eight or 10 times as much per gallon as had been found in any hot spring previously analysed – that scientists suspect “it may prove of great commercial value”.But 19th-Century England had little need for the element, and this 50C (122F) lithium-rich water continued steaming away in the dark for more than 150 years.Fast forward to autumn 2020, and a site nearby the Wheal Clifford in Cornwall has been confirmed as having some of the world’s highest grades of lithium in geothermal waters. The commercial use for lithium in the 21st Century could not be clearer. It is found not only inside smart phones and laptops, but is now vital to the clean energy transition, for the batteries that power electric vehicles and store energy so renewable power can be released steadily and reliably.",
		title: "The new 'gold rush' for green lithium",
	},
];

export default stories;
